### ISSUE TITLE
webui feedback

### ISSUE THREAD

**Issue by jbenet** [ipfs/webui#1]
This is an issue compiling a bunch of feedback in one place.

## Styling + Home

![](https://www.evernote.com/shard/s198/sh/e861c286-d80c-4d0c-8b21-d8c8aa640967/3264cfc86784f58ef0b7ff569ce79ae4/deep/0/IPFS-and-This-is-an-issue-compiling-a-bunch-of-feedback-in---go-ipfs.png)

Styling:
- [x] links still break url + back button... use hash or query string?
- [x] `fa-list` for logs
- [x] reduce sidebar nav font-weight (use `200` or `400`? maybe helvetica neue?)
- [x] reduce size of sidebar?
- [x] title or dag search bar at the top navbar
- [x] top navbar `10px` shorter
- [x] top right icons should have tool tips
- [x] add "Docs" top right icon

## Home

- [x] use `<code>` for all hashes (monospace).
- [x] use `<code>` for version identifiers
- [x] use `<pre>` for key
- [x] use `<code>` or `<pre>` for addresses

## Connections 

- [x] dont geolocate local addresses. treat them as self.
      (geolocate own addresses only if not local)
- [x] still not loads conns for me :(

## Files

![](https://www.evernote.com/shard/s198/sh/a4ac6a53-3448-4aac-84f2-565268f4b5a4/51dc71ee2c6258ad6969b11e99c07146/deep/0/IPFS.png)

- [x] drag+drop is super nice. but there's little indication that file was successfully added. maybe add a `<div class="alert alert-success">` with each filename.
- [ ] list all local unixfs files in this page.
- [x] hashes should be selectable (use `<code>`?), no need to link.
- [x] add a "DAG" (or maybe `fa-share-alt`) action, which takes you to object's dag page  
- [x] `Pinned Files` should be in its own page. it's going to get big.
- [x] `All Local Files` should be in its own page (Local Objects

## DAG

- [x] add to field: `placeholder="Enter hash or path: /ipfs/QmBpath..."`
- [ ] as user enters things, the field outline should color greein if a hash is correctly entered, and red if not. (some taeke a sec to be transmitted)
- [x] enter on the field should work
- [ ] needs an image when there is nothing selected.

## Config

![](https://www.evernote.com/shard/s198/sh/695e2e1e-22b1-4634-9409-2c487b3129f2/1432da333a53569353582f211be3f5d5/deep/0/IPFS-and-This-is-an-issue-compiling-a-bunch-of-feedback-in---go-ipfs.png)

- [x] move save btn to right
- [x] add a reset btn
- [x] add reset + save buttons to top right
- [x] make textarea arbitrarily large.

## Logs

![](https://www.evernote.com/shard/s198/sh/0b546c4d-4fcf-4073-871d-8453abdd2e28/638d718318d73f47360b5149aa47aa33/deep/0/IPFS-and-This-is-an-issue-compiling-a-bunch-of-feedback-in---go-ipfs.png)

- [x] use "Tail" instead of "Bottom". 
- [x] make it actually tail (add events + rescroll to end)
- [x] add "Clear" and "Top" to bottom of file
- [x] clear looks too faded. use same color. 
- [x] use` <pre>` for the text area, 
- [x] pretty-print each json item.
- [ ] use `js` syntax highlighting with GFM. (highlight.js?)

**Comment by jbenet** [comment]
_awesome_ progress! this looks great.

bugs: 
- [ ] copy to clipboard doesnt work and send me back to home page.
- [ ] ~~if i have many local addresses, it doesnt find me (location unknown). at least one of them is my external though. (filter local addrs too)~~ it was the ad blocker. maybe same alert?
- [ ] font color for config should be a bit darker
- [ ] If i press enter on the DAG input field i'm taken to home. url shows a modified route (`http://localhost:5001/ipfs/QmXkmaCYKvDhLS3wmUDJZF87ck4cuzpixc9iNSqx6Wh63i/#/objects//ipfs/QmXkmaCYKvDhLS3wmUDJZF87ck4cuzpixc9iNSqx6Wh63i`), so maybe the route handler isnt working right?
- [ ] the teal text color in the connections page isnt very readable (i know this is what the design called for.) maybe something darker? 
- [ ] maybe make the globe be `position: absolute` or `fixed` so that it stays with you as you scroll down the list of peers.
- [ ] would be awesome if we rotated globe to the given peer (and maybe colored it differently)  when we hover over their entry on the list. (but this is low prio / a nice to have.)

still saw 0 peers in connections page. my console says `Failed to load resource: net::ERR_BLOCKED_BY_CLIENT`. http://stackoverflow.com/questions/22318119/i-am-getting-failed-to-load-resource-neterr-blocked-by-client-with-google-chr says it's ad block. 
- [ ] connections page should still show list of connections / peers even if geolocs fail
- [ ] maybe display a note to the user if all geo-locs fail about ad-blocking? 

Maybe something like:
```
<div class="alert">
  Our calls to the geolocation service have been blocked. It's possible that ad-blocking software is mistakenly blocking these calls. Try disabling the ad-blocker on this page only. (Geolocation information is strictly for your own use in this page, that information is not sent anywhere.)
</div>
```

**Comment by whyrusleeping** [comment]
Would be really cool to have the config be a dynamic editable 'form-like' thing. Instead of just a textarea with json dumped in it

**Comment by whyrusleeping** [comment]
We also *really* shouldnt be displaying the private key in the webUI, theres no reason at all to have that there.

**Comment by jbenet** [comment]
> Would be really cool to have the config be a dynamic editable 'form-like' thing. Instead of just a textarea with json dumped in it

It's not as flexible. We had some fields before but that creates a mess of having to update the webui too every time we add any config field, and what to do when users add their own keys to the config, how to display complex fields (do sub-arrays or sub-objects get represented as fields or json?) 

> We also really shouldnt be displaying the private key in the webUI, theres no reason at all to have that there.

It's the public key. (or it should be)

**Comment by mappum** [comment]
Most of the comments have been addressed, the latest webui is `QmaaqrHyAQm7gALkRW8DcfGX3u8q9rWKnxEMmf7m9z515w`.

**Comment by whyrusleeping** [comment]
@jbenet the image under config in your top comment was showing the private key, just wanted to make sure that it stays out of any web UI, could be many potential security flaws if that happened

**Comment by mappum** [comment]
Well the private key should really just not be in the config, but in its own file.

**Comment by jbenet** [comment]
Yeah, until the private keys are in their own files, being listed in the
config page doesnt change things (it would still be accessible through the
config api).

**Comment by whyrusleeping** [comment]
The light green font on the dag browser is a little to light, its kindof hard to see against the white background

**Comment by BrendanBenshoof** [comment]
The map is a bit too dark to actually see things on.

**Comment by jbshirk** [comment]
webui shows 0 peers (and no globe) but ipfs swarm peers shows peers (and they are working)
![ipfs - connected to 0 peers](https://cloud.githubusercontent.com/assets/3949396/8651550/98673fbe-2947-11e5-82bf-dd0120885d02.png)

**Comment by whyrusleeping** [comment]
@jbshirk i'm guessing that your node might still be loading the geolocation data. Let me know if refreshing it helps after waiting a bit.

If thats the case, having a loading bar somewhere might be nice.

**Comment by waynenilsen** [comment]
i had the IPFS daemon running for about 10 mins and i still see what @jbshirk sees there

**Comment by jbenet** [comment]
something is _definitely_ acting up. i dont know what. i can reboot my daemon once or twice and then it works, but have been stuck too. !!!

**Comment by jbenet** [comment]
@whyrusleeping this isnt geolocation, the info tab remains empty for me

**Comment by jbenet** [comment]
(oh maybe you just fixed this?)

**Comment by Dignifiedquire** [comment]
@jbenet are you still having this issue? Can you open dev tools, reload and show the output?

**Comment by jbshirk** [comment]
my safari console dump, HTH

	[Warning] Unexpected CSS token: : (style.css, line 3475)
	[Warning] Unexpected CSS token: : (style.css, line 6136)
	[Warning] Unexpected CSS token: : (style.css, line 6145)
	[Warning] Unexpected CSS token: : (style.css, line 7104)
	[Warning] Unexpected CSS token: : (style.css, line 7110)
	[Warning] Unexpected CSS token: : (style.css, line 7116)
	[Warning] Unexpected CSS token: : (style.css, line 7122)
	[Warning] Unexpected CSS token: : (style.css, line 7128)
	[Log] Object (bundle.js, line 2225)
	
	[Error] Failed to load resource: the server responded with a status of 403 (Forbidden) (config, line 0)
	[Error] 403 - Forbidden
		(anonymous function) (bundle.js, line 2183)
		(anonymous function) (bundle.js, line 21709)
		emit (bundle.js, line 6430)
		handle (bundle.js, line 7115)
		onreadystatechange (bundle.js, line 6878)
	[Error] Failed to load resource: the server responded with a status of 403 (Forbidden) (version, line 0)
	[Error] 403 - Forbidden
		(anonymous function) (bundle.js, line 2192)
		(anonymous function) (bundle.js, line 21709)
		emit (bundle.js, line 6430)
		handle (bundle.js, line 7115)
		onreadystatechange (bundle.js, line 6878)
	[Error] Failed to load resource: the server responded with a status of 403 (Forbidden) (check, line 0)
	[Error] Failed to load resource: the server responded with a status of 403 (Forbidden) (tail, line 0)
	[Error] 403 - Forbidden
		(anonymous function) (bundle.js, line 1114)
		(anonymous function) (bundle.js, line 21709)
		emit (bundle.js, line 6430)
		handle (bundle.js, line 7115)
		onreadystatechange (bundle.js, line 6878)
	[Log] [LongUrl] [Allow] Domain "localhost" not found on blacklist (LongURL4Safari.js, line 105)
	[Log] Object (bundle.js, line 2225)
	
	[Error] Failed to load resource: the server responded with a status of 403 (Forbidden) (config, line 0)
	[Error] 403 - Forbidden
		(anonymous function) (bundle.js, line 1036)
		(anonymous function) (bundle.js, line 21709)
		emit (bundle.js, line 6430)
		handle (bundle.js, line 7115)
		onreadystatechange (bundle.js, line 6878)
	[Error] Failed to load resource: the server responded with a status of 403 (Forbidden) (id, line 0)
	[Error] 403 - Forbidden
		(anonymous function) (bundle.js, line 1016)
		(anonymous function) (bundle.js, line 21709)
		emit (bundle.js, line 6430)
		handle (bundle.js, line 7115)
		onreadystatechange (bundle.js, line 6878)

**Comment by Dignifiedquire** [comment]
@jbenet @jbshirk this should fix it: https://github.com/ipfs/webui/issues/88#issuecomment-149040893

**Comment by jbenet** [comment]
```
Failed to load resource: the server responded with a status of 403 (Forbidden)
bundle.js:2610 403 - Forbidden(anonymous function) @ bundle.js:2610
http://localhost:5001/api/v0/version?stream-channels=true Failed to load resource: the server responded with a status of 403 (Forbidden)
bundle.js:2619 403 - Forbidden(anonymous function) @ bundle.js:2619
http://localhost:5001/api/v0/update/check?stream-channels=true Failed to load resource: the server responded with a status of 403 (Forbidden)
http://localhost:5001/api/v0/id?stream-channels=true Failed to load resource: the server responded with a status of 403 (Forbidden)
bundle.js:1121 403 - Forbidden(anonymous function) @ bundle.js:1121
http://localhost:5001/api/v0/config?arg=Gateway.Enabled&stream-channels=true Failed to load resource: the server responded with a status of 403 (Forbidden)
bundle.js:1141 403 - Forbidden
```
forbiddens too.

@Dignifiedquire i shouldnt need to set CORS on this. it should work out of the box

**Comment by Dignifiedquire** [comment]
@jbenet I know, but that's the bug #88 is about, the default restrictions of go-ipfs are just too strict at the moment

**Comment by jbenet** [comment]
@Dignifiedquire i still dont understand. afaik this worked _fine_ out of the box after that commit you surfaced. something else changed in between. this shouldn't be a problem. the default restriction is correct. (may not be correctly implemented anymore)

other weird part is it _sometimes works_ and _sometimes doesn't_. this is very weird.

**Comment by Dignifiedquire** [comment]
@jbenet not sure what commit you are referring to. 

For me it hasn't worked since I started using ipfs except for when I added the hack from #88.

**Comment by jbenet** [comment]
@Dignifiedquire ah, now i understand you. the default is not -- as it should be -- `"http://localhost:5001"`.

this part though

> other weird part is it sometimes works and sometimes doesn't. this is very weird.

still very weird.

**Comment by Dignifiedquire** [comment]
> still very weird.

**very** weird, agreed

**Comment by Dignifiedquire** [comment]
@jbenet closing  this issue this is tracked in https://github.com/ipfs/go-ipfs/issues/1883 and #88
